# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98e854a45b9c5dacf54cd6075dfa8de8619dbcdc2272ce83cd6f840097df348ef8ed7d30b6dbb678e359fc161bee0406d965cfd8788462fbf0c45bf1715a5577

test:
  secret_key_base: 78ec8d2e185951ba800826ec0541efa3f08fe267dc24412de0e29210515fe4fafca71d82e90628fcba68c412d7a2c69eb8993edbba6b1b9f7f2a6103d76b6ac0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
